# docker-compose-emqx

version: '3'

services:
  emqx1:
    image: emqx/emqx:v4.3.5
    environment:
    - "EMQX_NAME=emqx_1"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.io"
    - "EMQX_ZONE__EXTERNAL__RETRY_INTERVAL=2s"
    - "EMQX_MQTT__MAX_TOPIC_ALIAS=10"
    volumes:
        - ./tmp/emqx.lic:/opt/emqx/etc/emqx.lic
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
    ports:
      - 1884:1883
      - 8081:8081
      - 8083:8083
      - 8883:8883
      - 18083:18083
networks:
      emqx-bridge:
      driver: bridge
